# Generated by Django 4.1.1 on 2022-09-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Product", new_name="Item",),
        migrations.RenameField(
            model_name="order", old_name="products", new_name="items",
        ),
    ]
