# Generated by Django 4.1.1 on 2022-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_session", models.CharField(max_length=32)),
                ("items", models.ManyToManyField(to="shop.item")),
            ],
        ),
    ]
